<a href="https://colab.research.google.com/github/KlayClarke/tf--experimentation/blob/main/data_generation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Generating Data

In [39]:
import numpy as np

In [40]:
# for a 2 x 3 array with all 0s
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
# for a 2 x 3 array with all 1s
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
# for a 2 x 3 array with all 10s
10 * np.ones((2,3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [43]:
# for a 3 x 3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
# for a random num
np.random.random()

0.8692131160234365

In [45]:
# for a 2 x 3 array with all randoms (notice only positives)
np.random.random((2,3))

array([[0.4350049 , 0.01917634, 0.46595741],
       [0.10293902, 0.33835549, 0.02729964]])

In [46]:
# for a 2 x 3 array with all randoms (includes negatives)
np.random.randn(2,3)

array([[ 0.50550243, -1.55691193, -1.45649379],
       [-0.7676872 ,  0.54426181,  0.75559229]])

In [47]:
# for a random array of 10000 numbers
R = np.random.randn(10000)

In [48]:
R

array([-0.5008789 ,  0.96287805,  0.56228407, ..., -1.52668007,
        0.8092718 , -1.18364385])

In [49]:
# mean
R.mean()

-0.0016267599385549822

In [50]:
# mean
np.mean(R)

-0.0016267599385549822

In [51]:
# variance
R.var()

0.9902387837593296

In [52]:
# square root of the variance
R.std()

0.9951074232259197

In [53]:
# for a 10000 x 3 array
R = np.random.randn(10000,3)

In [54]:
R

array([[ 2.69421418, -0.4892913 , -1.24979176],
       [ 1.09413926,  0.83465114,  1.06672597],
       [-0.21205359, -3.36472896,  1.40466571],
       ...,
       [ 1.50691165,  0.19309068, -0.95746697],
       [ 1.26852303, -0.22152283,  0.94469865],
       [ 1.2104417 ,  0.52567628, -0.2820504 ]])

In [55]:
# to calculate mean of each column
R.mean(axis=0)

array([ 6.17400819e-05,  1.08923463e-02, -2.52803525e-03])

In [56]:

R.mean(axis=1)

array([ 0.31837704,  0.99850546, -0.72403895, ...,  0.24751179,
        0.66389962,  0.48468919])

In [57]:
R.mean(axis=1).shape

(10000,)

In [58]:
# covariance
np.cov(R)

array([[ 4.37804183e+00,  1.26284504e-01,  5.51365030e-03, ...,
         2.46284664e+00,  8.55637076e-01,  1.44677145e+00],
       [ 1.26284504e-01,  2.03240498e-02,  3.13436442e-01, ...,
         2.35770327e-02,  1.11029490e-01,  5.19159703e-03],
       [ 5.51365030e-03,  3.13436442e-01,  5.88337815e+00, ...,
        -8.88270164e-01,  1.62271138e+00, -6.84410843e-01],
       ...,
       [ 2.46284664e+00,  2.35770327e-02, -8.88270164e-01, ...,
         1.52051174e+00,  2.35645723e-01,  9.17843487e-01],
       [ 8.55637076e-01,  1.11029490e-01,  1.62271138e+00, ...,
         2.35645723e-01,  6.14195240e-01,  9.36081668e-02],
       [ 1.44677145e+00,  5.19159703e-03, -6.84410843e-01, ...,
         9.17843487e-01,  9.36081668e-02,  5.58143126e-01]])

In [59]:
np.cov(R).shape

(10000, 10000)

In [60]:
np.cov(R.T)

array([[ 1.01265576e+00, -1.32440740e-02, -1.25775184e-02],
       [-1.32440740e-02,  1.00254492e+00,  7.10317400e-05],
       [-1.25775184e-02,  7.10317400e-05,  1.01304594e+00]])

In [61]:
np.cov(R, rowvar=False)

array([[ 1.01265576e+00, -1.32440740e-02, -1.25775184e-02],
       [-1.32440740e-02,  1.00254492e+00,  7.10317400e-05],
       [-1.25775184e-02,  7.10317400e-05,  1.01304594e+00]])

In [62]:
# for 3 x 3 array with random ints from 0 to 10
np.random.randint(0,10,size=(3,3))

array([[1, 8, 4],
       [0, 5, 5],
       [3, 8, 1]])

In [63]:
# for 3 x 3 array with random ints from 0 to 10
np.random.choice(10, size=(3,3))

array([[0, 5, 7],
       [9, 6, 0],
       [8, 5, 1]])