<a href="https://colab.research.google.com/github/KlayClarke/tf--experimentation/blob/main/numpy__intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Intro

In [3]:
# an introduction to the NumPy stack
# NumPy (raw materials), SciPy (statistics), matplotlib (data visualization) and Pandas (reading, writing, manipulating)

In [4]:
import numpy as np
L = [1,2,3]

In [5]:
A = np.array([1,2,3])

In [6]:
print(L)

[1, 2, 3]


In [7]:
print(A)

[1 2 3]


In [ ]:
# loop over list / array

In [8]:
for e in L:
  print(e)

1
2
3


In [9]:
for e in A:
  print(e)

1
2
3


In [12]:
# adding new items to list / array -- impossible in np (must create new array instead)

In [13]:
L.append(4)

In [14]:
print(L)

[1, 2, 3, 4]


In [27]:
# to add number to each el in list / array
L2 = []
for e in L:
  L2.append(e + 3)
print(L2)

[4, 5, 6, 7]


In [25]:
# or
L3 = [e + 3 for e in L]
print(L3)

[4, 5, 6, 7]


In [28]:
# to square each el in list
L4 = [e ** 2 for e in L]
print(L4)

[1, 4, 9, 16]


In [29]:
A**2 

array([1, 4, 9])

In [30]:
# sqrt of els in np array
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [31]:
# logs of els in np array
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [32]:
# exp of els in np array
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [33]:
# hyperbolid tension
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

## The Dot Product

In [34]:
a = np.array([1,2])
b = np.array([3,4])

In [35]:
dot = 0
for e, f in zip(a, b):
  dot += e * f
dot

11

In [41]:
new_dot = 0
for i in range(len(a)):
  new_dot += a[i] * b[i]
new_dot

11

In [42]:
np.sum(a * b)

11

In [43]:
(a*b).sum()

11

In [45]:
np.dot(a, b)

11

In [46]:
a.dot(b)

11

In [47]:
a @ b

11

In [49]:
# a magnitude
amag = np.sqrt((a*a).sum())
amag

2.23606797749979

In [50]:
# norm of vector a
np.linalg.norm(a)

2.23606797749979

In [58]:
# cosine of angle of vector
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))
cosangle

0.9838699100999074

In [57]:
# angle (radians)
angle = np.arccos(cosangle)
angle

0.17985349979247847