<a href="https://colab.research.google.com/github/KlayClarke/tf--experimentation/blob/main/data_generation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Generating Data

In [1]:
import numpy as np

In [2]:
# for a 2 x 3 array with all 0s
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
# for a 2 x 3 array with all 1s
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [4]:
# for a 2 x 3 array with all 10s
10 * np.ones((2,3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [5]:
# for a 3 x 3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
# for a random num
np.random.random()

0.7302895579905949

In [7]:
# for a 2 x 3 array with all randoms (notice only positives)
np.random.random((2,3))

array([[0.48543298, 0.38863307, 0.79647443],
       [0.90570898, 0.58159322, 0.24011309]])

In [8]:
# for a 2 x 3 array with all randoms (includes negatives)
np.random.randn(2,3)

array([[-0.9389472 , -1.2984729 , -0.41636587],
       [-0.31970654, -0.57178591, -0.7416501 ]])

In [9]:
# for a random array of 10000 numbers
R = np.random.randn(10000)

In [10]:
R

array([ 1.65694127, -0.21112796, -1.07315829, ...,  0.11091934,
        1.70942878,  0.56242482])

In [11]:
# mean
R.mean()

-0.012263878201927267

In [12]:
# mean
np.mean(R)

-0.012263878201927267

In [13]:
# variance
R.var()

1.0387807844644388

In [14]:
# square root of the variance
R.std()

1.019205957824246

In [15]:
# for a 10000 x 3 array
R = np.random.randn(10000,3)

In [16]:
R

array([[ 0.56624401,  0.12254136, -0.91320906],
       [ 0.67911585,  0.43602471, -2.26545642],
       [-0.28971397,  1.05734494, -0.34965369],
       ...,
       [ 0.35074197,  0.33858967, -0.96033356],
       [-1.16870555, -0.78455655,  0.90644382],
       [ 0.50626373,  2.03217463,  1.02237873]])

In [17]:
# to calculate mean of each column
R.mean(axis=0)

array([0.00591763, 0.01380547, 0.01370903])

In [18]:

R.mean(axis=1)

array([-0.0748079 , -0.38343862,  0.13932576, ..., -0.09033397,
       -0.34893942,  1.18693903])

In [19]:
R.mean(axis=1).shape

(10000,)

In [20]:
# covariance
np.cov(R)

array([[ 0.57640539,  1.21037947,  0.1580473 , ...,  0.5484045 ,
        -0.83199806, -0.06578702],
       [ 1.21037947,  2.67126657,  0.6083365 , ...,  1.22875455,
        -1.79533601,  0.13954521],
       [ 0.1580473 ,  0.6083365 ,  0.6329676 , ...,  0.31496647,
        -0.33102462,  0.57422292],
       ...,
       [ 0.5484045 ,  1.22875455,  0.31496647, ...,  0.56771138,
        -0.82030425,  0.10273971],
       [-0.83199806, -1.79533601, -0.33102462, ..., -0.82030425,
         1.21888293, -0.0083954 ],
       [-0.06578702,  0.13954521,  0.57422292, ...,  0.10273971,
        -0.0083954 ,  0.60241109]])

In [21]:
np.cov(R).shape

(10000, 10000)

In [22]:
np.cov(R.T)

array([[0.99347471, 0.00803474, 0.01350222],
       [0.00803474, 0.98183496, 0.01257204],
       [0.01350222, 0.01257204, 0.99047242]])

In [23]:
np.cov(R, rowvar=False)

array([[0.99347471, 0.00803474, 0.01350222],
       [0.00803474, 0.98183496, 0.01257204],
       [0.01350222, 0.01257204, 0.99047242]])

In [24]:
# for 3 x 3 array with random ints from 0 to 10
np.random.randint(0,10,size=(3,3))

array([[9, 5, 9],
       [0, 4, 8],
       [0, 8, 4]])

In [25]:
# for 3 x 3 array with random ints from 0 to 10
np.random.choice(10, size=(3,3))

array([[9, 1, 0],
       [9, 1, 7],
       [5, 6, 3]])