In [86]:
from datetime import datetime
import numpy as np

# create random matrices (3 x 3)
A = np.random.randint(0,10, size=(3,3))
B = np.random.randint(0,10, size=(3,3))
T = 1000000

In [87]:
print(A)
print(B)

[[5 3 3]
 [0 6 6]
 [8 3 5]]
[[2 7 2]
 [2 0 8]
 [5 3 0]]


In [88]:
def slow_matrix_multiplication(a,b):
  result = np.zeros((3,3))
  # iterate over rows of b
  for i in range(len(a)):
    # iterate over columns of b
    for j in range(len(b[0])):
      # iterate over rows of b
      for k in range(len(b)):
        # add results to zeroed results matrices initialized above
        result[i][j] += a[i][k] * b[k][j]
  return result


In [89]:
# PYTHON TEST

# record initial time
t0 = datetime.now()
# run test
for t in range(T):
  slow_matrix_multiplication(A,B)
# calculate time elapsed
dt1 = datetime.now() - t0

In [90]:
# NUMPY TEST

# record initial time
t0 = datetime.now()
# run test
for t in range(T):
  np.matmul(A,B)
# calculate time elapsed
dt2 = datetime.now() - t0

In [91]:
# calculate time differential
print("dt1/dt2:", dt1.total_seconds()/dt2.total_seconds())

dt1/dt2: 28.745268740548074


In [92]:
# compare results of both functions
print(np.matmul(A,B) == slow_matrix_multiplication(A,B))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
