<a href="https://colab.research.google.com/github/KlayClarke/tf--experimentation/blob/main/numpy__matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

In [8]:
# matrix must be 2 dimensional
L = [[1,2], [3,4]]
L

[[1, 2], [3, 4]]

In [9]:
L[0]

[1, 2]

In [10]:
L[0][1]

2

In [16]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [19]:
A[0][1]

2

In [20]:
A[0,1]

2

In [23]:
# return column at specific index of matrix
A[:,0]

array([1, 3])

In [24]:
A.T

array([[1, 3],
       [2, 4]])

In [25]:
A

array([[1, 2],
       [3, 4]])

In [26]:
# exp of el in matrix
np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [28]:
# same done to list
np.exp(L)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [31]:
# create matrix
B = np.array([[1,2,3],[4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
# matrix multiplication
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [40]:
# see error
A.dot(B.T)

ValueError: ignored

In [42]:
# matrix determinate
np.linalg.det(A)

-2.0000000000000004

In [43]:
# matrix inverse
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [44]:
# matrix identity
np.linalg.inv(A).dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [45]:
# matrix trace
np.trace(A)

5

In [46]:
# diagonal el
np.diag(A)

array([1, 4])

In [47]:
np.diag([1,4])

array([[1, 0],
       [0, 4]])